spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Diplom
    username: postgres
    password: postgres
  flyway:
    baseline-on-migrate: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

workTime:
  #Hour
  start: 8
  #Hour
  end: 17
  #Minute
  step: 1